---
- hosts: front
  gather_facts: True
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
  roles:
    - servertuning  
    - base
    - nginx
    - phpfpm
    - mongodbcommon
    - mongo
    - filebeat
    - omd_agent

      
    
