---
- name: get ethernet
  shell: echo eth$((`lspci | grep -i ether | wc -l`-1))
  register: ethno
  
- name: update network for static ip
  blockinfile:
    path: /etc/network/interfaces
    marker: "# {mark} static ip variables"
    block: |
        auto {{ ethno.stdout }}
        iface {{ethno.stdout}} inet static
            address {{ private_ip }}
            netmask {{ netmask }}
        
- name: ifup
  shell: "sudo ifup {{ ethno.stdout }}"
  ignore_errors: yes  
