

filebeat.prospectors:
- input_type: log
  paths: /mnt/consume.log
  json.keys_under_root: true
  input_type: log
  ignore_older: 1h
  scan_frequency: 1s
  harvester_buffer_size: 131072
  close_eof: true
  clean_removed: true
  close_inactive: 10m
- input_type: log
  paths: /tmp/error_log_beat.log
  document_type: track
  json.keys_under_root: true
  input_type: log
  ignore_older: 1h
  scan_frequency: 1s
  harvester_buffer_size: 131072
  close_eof: true
  clean_removed: true
  close_inactive: 10m
processors:
- drop_fields:
    fields: ["beat", "input_type"]

output.elasticsearch:
  hosts: ["{{ es_ip }}:{{ es_port }}"]
  #template.overwrite: true
  indices:
    - index: "consume-%{+yyyy.MM.dd}"
      when.contains:
        "ltp": "bo"
    - index: "logbeat-%{+yyyy.MM.dd}"
      when.contains:
        "case": "init"
    - index: "tracking"
      when.contains:
        "case": "update"
    - index: "errorlog"
  bulk_max_size: 2048
logging: 
  files: 
    keepfiles: 5
    name: filebeat.log
    path: /var/log/filebeat
    rotateeverybytes: 10485760
  level: info
  to_files: true
  to_syslog: false
filebeat.spool_size: 16384
filebeat.shutdown_timeout: 5s
filebeat.idle_timeout: 5s
queue_size: 2000