---
- name: install all apt packages 
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
      - mcrypt
      - librabbitmq-dev
      - php
      - php-intl
      - php-json
      - php-mcrypt
      - php-pear
      - python-pip
      - python-dev
      - pkg-config
      - unzip
      - libssl-dev
      - libsslcommon2-dev
      - git
      - php7* 
      - awscli
  when: apt_pkg_install == True
  ignore_errors: yes
  
