---
- name: install pear libaries.
  shell: "yes \"\" | pear install {{ item }}"
  register: pear_result
  changed_when: "pear_result.rc == 0"
  failed_when:  "not (('already installed' in pear_result.stdout) or ('install ok:' in pear_result.stdout))"
  with_items:
      - Crypt_HMAC
      - Crypt_HMAC2
      - Benchmark
      - HTTP_Request
      - HTTP_Request2
      - Crypt_HMAC2
  ignore_errors: yes
  when: pear_pkg_install == True
